try(o foo)
    {
        on(MyException e)
        [
            // handle exceptions of type MyException and derived
        ]
    }
